import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import imgDiego from "../public/prefil Diego.jpg";
import web1 from "../public/interactive detail from.png";
import web2 from "../public/shorteningUrl.png";
import web3 from "../public/countries.png";
import web4 from "../public/modernuiux.png";
import web5 from "../public/ai-image.png";
import web6 from "../public/memories-app.png";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Diego Cuevas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              Diego Cuevas
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 cursor-pointer"
                  href="./currículum-DiegoCuevas.pdf"
                  download="Cv Diego Cuevas.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Diego Cuevas
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Frontend Developer
            </h3>
            <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 my-20 mx-auto overflow-hidden md:h-96 md:w-96">
              <Image
                src={imgDiego}
                layout="fill"
                alt="profile pic"
                objectFit="cover"
              />
            </div>
            <p className="text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-white">
              I am Diego Cuevas and I am a Frontend Web Developer.!
            </p>
            <p className="text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-white">
              I formed myself in the SoyHenry bootcamp, an intensive course for
              Full-Stack Web Developer, which counts with 800+ hours of
              practicing and learning, additional I have training in platzi,
              freecodecamp and codecademy in frontend technologies. High
              attention to details, adaptability and very good communication
              skills.
            </p>
            <p className="text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-white">
              I want to continue my growth as a professional in the area of
              ​​Frontend Development. I am looking for continue improving my
              skills 💪
            </p>
            <p className="text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-white">
              💻Which technologies do I work with? <br />
              <br /> ◽Languages: Javascript, SQL <br /> ◾Front-End : React |
              Redux | Hooks | React-Router | Bootstrap | CSS | TailwindCss |
              MaterialUI <br /> ◽Back-End : Node.js | Express | <br />{" "}
              ◾DataBase: SEQUELIZE | PostgreSQL | MongoDB
            </p>
          </div>
        </section>

        {/* section two */}
        {/*  <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">
              Services I offer
            </h3>
            <p className="text-md py-2  leading-8 text-gray-800 dark:text-white">
              Que trabajos he hecho y ponerlos acá
            </p>
          </div>
          <div className="lg:flex gap-10 justify-center  rounded-xl">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={code}
                width={100}
                height={100}
                alt="trabajos realizados"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">Trabajos realizados de desarrollo</p>
              <h4 className="py-4 text-teal-600">Develop tools</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
          </div>
        </section> */}
        <section>
          <div>
            <h3 className="text-5xl py-1 mt-10 dark:text-teal-600">
              Portfolio
            </h3>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href="https://memories-app-client-nine.vercel.app"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web6}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://ai-image-generation-app.vercel.app/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web5}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <a
                href="https://countries-app-deploy-client.vercel.app/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web3}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://modernuisite.netlify.app/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web4}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://apishorteningurl.netlify.app/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web2}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://sage-choux-aa4147.netlify.app/"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={web1}
                  alt="imagen de portafolio"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>

            {/* <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="imagen de portafolio"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="imagen de portafolio"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div> */}
          </div>
        </section>
        <footer className="text-teal-600  text-center pb-10">
          <h1 className="mt-10 text-5xl">Contact</h1>
          <p className="text-xl pt-5">Email: ingdcuevas@gmail.com</p>
          <p className="text-xl pt-3">Phone number: +573202680705</p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white ">
            <a
              className="hover:text-teal-600"
              href="https://github.com/Dfcuevas"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub />
            </a>
            <a
              className="hover:text-teal-600"
              href="https://www.linkedin.com/in/diego-fernando-cuevas-frontend-developer/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin />
            </a>
          </div>
        </footer>
      </main>
    </div>
  );
}
